"""empty message

Revision ID: 8cf0526033bb
Revises: 26953147f8b9
Create Date: 2026-03-31 21:01:34.919227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cf0526033bb'
down_revision: Union[str, None] = '26953147f8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=64), nullable=False))
    op.add_column('users', sa.Column('father_name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_father_name'), 'users', ['father_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_father_name'), table_name='users')
    op.drop_column('users', 'father_name')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
